# fly.toml app configuration file generated for mba-fiap-nats-cluster on 2024-05-07T23:16:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mba-fiap-nats-cluster'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8222
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 4222
  protocol = 'tcp'

  [[services.ports]]
    port = 4222

[[vm]]
  size = 'shared-cpu-1x'
