services:
  db:
    image: postgres:16.0
    restart: always
    container_name: pg-postgres
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

