services:
  nats:
    image: nats:2.10.14-alpine
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  db:
    image: postgres:16.0
    restart: always
    container_name: pg-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - default

  lanchonete:
    build: .
    depends_on:
      - db
    volumes:
      - m2-repo:/usr/share/maven

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - HTTP_PORT=8080
    networks:
      - default
    ports:
      - "8080:8080"

    command: ["prod"]
volumes:
  m2-repo:



