sequenceDiagram
%% Nodes
    participant C as Cliente
    participant L as Lanchonete
    participant N as NATS Broker
    participant S as Pagamento
    participant P as Preparo


    C ->>+L: 1. Solicitar pagamento (conclusão do pedido)
    L ->> N: 2. pagamento.novo-pedido
    N ->> S: 3. pagamento.novo-pedido(processar pedido de pagamento)
    S ->> N: 4. pagamento.status
    loop Processar status
        N ->> L: 5. pagamento.status (persiste status do pagamento)
    end
    L ->> N: 6. pedido.novo-preparo (pedido pronto para preparo)
    N ->> P: 7. pedido.novo-preparo (pedido pronto para preparo)
    P ->> N: 8. pedido.status (pedido em preparo)
    loop Processar status
        N ->> L: 9. pedido.status (persiste status do pedido)
    end
    N ->> L: 10. pedido.preparado (pedido pronto)

