apiVersion: v1
kind: Service
metadata:
  name: lanchonete # Sets service name
  labels:
    app: lanchonete # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 8080 # Sets port to run the postgres application
      targetPort: lanchonete-port
  selector:
    app: lanchonete