apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-config
  labels:
    app: lanchonete
data:
  HTTP_PORT: ${HTTP_PORT}
  ## "8080"
  POSTGRES_PORT: "5432"
  ## "5432"
  POSTGRES_DB: ${POSTGRES_DB}
  ## "postgresdb"
  POSTGRES_USER: ${POSTGRES_USER}
  ## "postgres"
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ## "psltest"
  POSTGRES_HOST: ${POSTGRES_HOST}
  LAMBDA_URL: ${LAMBDA_URL}