apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: lanchonete
          image: lanchonete:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 200m
          ports:
            - containerPort: 8080 # Exposes container port
              name: lanchonete-port
          readinessProbe:
            httpGet:
              path: /produtos/lanche
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
          envFrom:
            - configMapRef:
                name: lanchonete-config

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: lanchonete
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: lanchonete
 minReplicas: 1
 maxReplicas: 20
 metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 60
   - type: Resource
     resource:
       name: memory
       target:
         type: AverageValue
         averageValue: 500Mi
   - type: Object
     object:
       metric:
         name: requests-per-second
       describedObject:
         apiVersion: networking.k8s.io/v1beta1
         kind: Ingress
         name: main-route
       target:
         type: Value
         value: 10k
 behavior:
  scaleDown:
    policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60