apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-config
  labels:
    app: lanchonete
data:
  HTTP_PORT: "8080"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgresdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "psltest"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"