apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-config
  labels:
    app: lanchonete
data:
  HTTP_PORT: ${HTTP_PORT}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  LAMBDA_URL: ${LAMBDA_URL}