apiVersion: v1
kind: Service
metadata:
  name: lanchonete # Sets service name
  labels:
    app: lanchonete # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - port: 8080
      targetPort: lanchonete-port
  selector:
    app: lanchonete